name: deploy vue
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build placeholder
        run: |
          mkdir -p dist
          echo "<html><head><title>Alina's Vue App</title></head><body style='background:#41b883;color:white;display:flex;flex-direction:column;justify-content:center;align-items:center;height:100vh;font-family:sans-serif;'><h1>✅ Alina's Vue Project Deployed!</h1><p>Continuous Deployment is working perfectly.</p><div style='margin-top:20px;'><button onclick='alert(\"Home Page\")'>Home</button> <button onclick='alert(\"Profile\")'>Profile</button></div></body></html>" > dist/index.html

      - name: Fix server permissions (Open door)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          key: ${{secrets.SSH_KEY}}
          script: sudo chown -R ubuntu:ubuntu /var/www/html

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}} 
          key: ${{secrets.SSH_KEY}}
          source: "./dist/*"
          target: "/var/www/html"
          strip_components: 1

      - name: Restore server permissions (Close door)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          key: ${{secrets.SSH_KEY}}
          script: sudo chown -R root:root /var/www/html
